services:
  postgres:
    image: postgres:16-alpine
    container_name: cadastro-credito-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-credito_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-credito_pass}
      POSTGRES_DB: ${POSTGRES_DB:-cadastro_credito}
    ports:
      - '${POSTGRES_PORT:-5433}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-credito_user} -d ${POSTGRES_DB:-cadastro_credito}']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
