export const CREDIT_REQUEST_STATUSES = [
  'DRAFT',
  'SUBMITTED_TO_MANAGER',
  'MANAGER_REVIEW',
  'RETURNED_TO_CONSULTANT',
  'SUBMITTED_TO_CREDIT',
  'CREDIT_REVIEW',
  'RETURNED_TO_MANAGER',
  'APPROVED',
  'REJECTED',
  'SIGNATURE_PENDING',
  'SIGNED',
  'COMPLETED',
  'CANCELLED',
] as const
export type CreditRequestStatus = (typeof CREDIT_REQUEST_STATUSES)[number]
